name: Automated Testing
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Install modules
        run: npm install
      - name: Run webpack
        run: npm run webpack
      - name: Run tests
        run: npm run test:unit
      - run: echo "This job's status is ${{ job.status }}."  